#pragma config(Sensor, S1,     uS,             sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorB,          right,         tmotorEV3_Large, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main () {
	setMotorSyncEncoder(left, right, 0, 1000, 50);
	sleep(1500);
}
